apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: helk1111/feoptimisationenergie
      context: ../projetoptimisationenergitique
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
