apiVersion: v1
kind: Service
metadata:
  name: feoptimisationenergie
  namespace: MyK8
  labels:
    app: feoptimisationenergie
spec:
  selector:
    app: feoptimisationenergie
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
